name: Trigger Release Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Trigger release.yml workflow
        run: |
          gh workflow run release.yml -f test_release=true --ref 3-refactoring-workflow --ref ${{ env.BRANCH_NAME }}"
